export const data = [
  {
    id: "1",
    title: "Manicure",
    img: "https://dev-boka-files.s3.amazonaws.com/SL/category/Manicure.svg",
    price: "$140",
    discription: "Our deluxe manicure includes shaping,scrube,hand mask",
  },
  {
    id: "2",
    title: "Pedicure",
    img: "https://dev-boka-files.s3.amazonaws.com/SL/category/padicure.svg",
    price: "$130",
    discription: "Our deluxe Pedicure includes shaping,scrube,hand mask",
  },
  {
    id: "3",
    title: "IV Therphy ",
    img: "https://dev-boka-files.s3.amazonaws.com/SL/category/iv%20therapy.svg",
    price: "$150",
    discription: "Our deluxe IV Therphy includes shaping,scrube,hand mask",
  },
  {
    id: "4",
    title: "Blowout",
    img: "https://dev-boka-files.s3.amazonaws.com/SL/category/blowout.svg",
    price: "$200",
    discription: "Our deluxe Blowout includes shaping,scrube,hand mask",
  },
  {
    id: "5",
    title: "Massage",
    img: "https://dev-boka-files.s3.amazonaws.com/SL/category/Massage.svg",
    price: "$135",
    discription: "Our deluxe Massage includes shaping,scrube,hand mask",
  },
  {
    id: "6",
    title: "Hairdresser",
    img: "https://dev-boka-files.s3.amazonaws.com/SL/category/haircut%201.svg",
    price: "$110",
    discription: "Our deluxe Hairdresser includes shaping,scrube,hand mask",
  },
  {
    id: "7",
    title: "Spa",
    img: "https://dev-boka-files.s3.amazonaws.com/SL/category/spa.svg",
    price: "$250",
    discription: "Our deluxe Spa includes shaping,scrube,hand mask",
  },
];
